name: CI guardrails
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with: { node-version: '22' }
      - name: Check merge markers
        run: |
          if git grep -nE '<<<<<<<|=======|>>>>>>>' -- .; then
            echo "::error::Remove merge-conflict markers"; exit 1; fi
      - name: Validate JSON files
        run: |
          node -e "JSON.parse(require('fs').readFileSync('package.json','utf8'))"
          echo "JSON ok"
      - name: Minimal function smoke (exists & exports)
        run: |
          for f in netlify/functions/ai-ping.js netlify/functions/ai-quick.js; do
            [ -f "$f" ] || { echo "::error::$f missing" ; exit 1; }
            grep -q 'export async function handler' "$f" || { echo "::error::$f has no handler export"; exit 1; }
          done
